name: Deploy Cloud Function

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm ci

    - name: Deploy a Cloud Function
      uses: google-github-actions/deploy-cloud-functions@v0.1.0
      with:
        name: cms
        runtime: nodejs14
        entry_point: cmsEntry
        credentials: ${{ secrets.gcp_credentials }}
